Rtti/transfer
nsubaru/Cardinal pull request #11
Opened 2022-08-24 00:45 UTC by nsubaru

Transfered:
- [x] CTTI::Object
- [x] RTTI 
- [x] StructCttiDef for Cardinal::Time
- [x] StructCttiDef for Settings::SettingsData
- [x] InitializerList from MSVC sources (copyrights saved)

Fixed:
- [x] CTTI compilation
- [x] warning in Math::SafeInt

Optimizations:
- [x] CTTI data generation for structs

Disabled:
- [x] Some warnings as they appear in each file because MSVC ignore #pragma warning disable

CoAuthors: @MonsterFich

2022-08-24 08:24 UTC, Alkoihor approved these changes

2022-08-25 09:58 UTC, MonsterFich requested changes
Cardinal.RTTI.Dynamic.Serialization.ixx - 16 -> export
Cardinal.RTTI.MetaData.Struct.ixx - 19 -> export

2022-08-25 11:07 UTC, Nelyndir approved these changes

2022-08-25 11:26 UTC, Oss1r approved these changes

2022-08-25 12:17 UTC, MonsterFich approved these changes

2022-08-25 12:17 UTC, merged