Added Crypt and Hash files.
nsubaru/Cardinal pull request #5
Opened 2022-08-14 14:55 UTC by Alkoihor

Added:

- [ ] Crypt files,
- [ ] Hash files.

Fixed:

- [ ] Containers.

2022-08-14 21:12 UTC, nsubaru approved these changes

2022-08-15 08:52 UTC, Oss1r approved these changes

2022-08-15 09:15 UTC, MonsterFich requested changes
Please fix formatting in SHA256 file.

2022-08-15 12:01 UTC, Alkoihor commented
@MonsterFich Done

2022-08-15 12:05 UTC, MonsterFich approved these changes

2022-08-15 15:08 UTC, merged